### PR TITLE
fix(ui): update banner text when auth and donor

### LINKED ISSUE #689: Donating users see the authenticated Banner instead
Although the related cookies are present, the donor banner is not displayed. 

Screenshot 2023-07-24 at 2 29 35 PM

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #689

It seemed like if a user was authenticated, they would see the authentication banner regardless if they were a donor. This should fix it.

### CODE REVIEW

File: src/_includes/assets/js/banner.js [hunk 1]
```diff
@@ -28,12 +28,12 @@ document.addEventListener('DOMContentLoaded', () => {
...
 
   // eslint-disable-next-line no-undef
-  if (isAuthenticated) {
+  if (isAuthenticated && !isDonor) {
     bannerTextNode.innerHTML = bannerAuthText;
     bannerAnchor.href = bannerAuthLink;
     bannerAnchor.setAttribute('text-variation', 'authenticated');
     // eslint-disable-next-line no-undef
-  } else if (isDonor) {
+  } else if (isAuthenticated && isDonor) {
```
Comment (naomi-lgbt) [inline src/_includes/assets/js/banner.js]: Pretty sure they can't be a donor without being authenticated.

Comment (a2937) [reply src/_includes/assets/js/banner.js]: While it simplifies that way, I like things explicitly spelled out.

Comment (naomi-lgbt) [reply src/_includes/assets/js/banner.js]: In that case, we should nest it:

```js
if (isAuthenticated) {
  bannerTextNode.innerHTML = isDonor ? bannerDonorText : bannerAuthText
}
else {
  bannerTextNode.innerHTML = bannerDefaultText
}
```

(Or reorder the whole thing so the default is the initial value instead of the fallback)

Comment (raisedadead) [reply src/_includes/assets/js/banner.js]: I agree it reads better.

**Review by raisedadead — DISMISSED** [review]
LGTM. We should probably expand the tests?

**Comment by a2937** [comment]
Yeah I'd like to expand the tests too. The biggest barrier to my expanding of the tests right this moment is a lack of intellisense in Visual Studio Code. It makes me feel better about the code I'm writing.

**Comment by a2937** [comment]
It was a _lot_ harder to write it without Typescript but it seems to have worked.

**Review by raisedadead — APPROVED** [review]
